version: '3'
services:
    
    client:
        build: ./client
        ports:
            - '8081:80'
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - api

    api:
        build: ./api
        ports:
            - '8080:3000'
        links:
            - redis
        expose:
            - 6379
        environment:
            - REDIS_URL=redis://cache
            - DEV_PORT=3000
            - DEV_REDIS_PORT=6379
            - DEV_REDIS_HOST=redis
        depends_on:
            - redis

    redis:
        image: redis
        container_name: cache
        command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
        restart:
            always
